### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by rishilss99** [Johnqczhang/densepose_installation#6]
cmake: /home/rishilss/Downloads/gcc-4.9.2/build/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by cmake)
cmake: /home/rishilss/Downloads/gcc-4.9.2/build/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by cmake)
cmake: /home/rishilss/Downloads/gcc-4.9.2/build/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libjsoncpp.so.1)

**I followed the exact steps mentioned in the guide but ran into this error when compiling the custom operator. Please help.**

**Comment by Johnqczhang** [comment]
Which version of `cmake` did you install? It seems that your installed `cmake` is not compatible with your installed `gcc`.

**Comment by rishilss99** [comment]
Should I build cmake from source or should I install cmake from anaconda. The system cmake is currently at 3.5.1 version
Thanks

**Comment by Johnqczhang** [comment]
You can try to download the cmake zip file at specific version from the [official website](https://cmake.org/files/). FYI, I used cmake-3.8.2 to build DensePose

**Comment by rishilss99** [comment]
Thanks for the help. I was able to finally compile custom operator using using cmake from conda itself.
`conda install cmake`

**Comment by wine3603** [comment]
i met the same problem, I did conda install cmake, and it is 3.14.0 in conda, but still the same error of missing GLIBCXX_3.4.21'

**Comment by wine3603** [comment]
> Thanks for the help. I was able to finally compile custom operator using using cmake from conda itself.
> `conda install cmake`

may I ask which cmake version were you using in your conda

**Comment by wine3603** [comment]
finally I past the zero_even_op.py test, get rid of the 

> OSError: /home/zhang-u16/DensePose/build/libcaffe2_detectron_custom_ops_gpu.so: undefined symbol: _ZN6caffe219CPUOperatorRegistryB5cxx11Ev

my final settings:

- `-- Found CUDA: /usr/local/cuda-8.0 (found version "8.0") 
- -- Caffe2: CUDA detected: 8.0
- -- Caffe2: CUDA nvcc is: /usr/local/cuda-8.0/bin/nvcc
- -- Caffe2: CUDA toolkit directory: /usr/local/cuda-8.0
- -- Caffe2: Header version is: 8.0
- -- Found CUDNN: /home/zhang-u16/anaconda3/pkgs/cudnn-7.6.0-cuda9.0_0/include  
- -- Found cuDNN: v7.6.0  (include: /home/my-u16/anaconda3/pkgs/cudnn-7.6.0-cuda9.0_0/include, library: /home/zhang-u16/anaconda3/pkgs/cudnn-7.6.0-cuda9.0_0/lib/libcudnn.so.7.6.0)
- -- Autodetected CUDA architecture(s):  6.1 6.1 6.1
- -- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
- -- Summary:
- --   CMake version        : 3.14.0
- --   CMake command        : /home/my-u16/anaconda3/envs/densepose/bin/cmake
- --   System name          : Linux
- --   C++ compiler         : /home/my-u16/gcc-4.9.2/build/bin/g++
- --   C++ compiler version : 4.9.2
- --   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
- --   Caffe2 version       : 1.1.0
- --   Caffe2 include path  : /home/my-u16/anaconda3/envs/densepose/lib/python3.7/site-packages/torch/include
- --   Caffe2 found CUDA    : True
- --     CUDA version       : 8.0
- --     CuDNN version      : 7.6.0
- -- Configuring done
- -- Generating done

`

the bug was from g++ 5.4.0. since I have two gcc installed, to tell cmake(3.14.0 from conda install cmake) use the version of 4.9.2, I did:
`cmake -DCMAKE_C_COMPILER="/home/my-u16/gcc-4.9.2/build/bin/gcc" -DCMAKE_CXX_COMPILER="/home/my-u16/gcc-4.9.2/build/bin/g++" ..
`
note that, set compiler path in CMakeLists.txt doesn't work for me, e.g.
`#SET(CMAKE_CXX_COMPILER "/home/zhang-u16/gcc-4.9.2/build/bin/g++")`

PS: this cmke-gui cannot work, since the `GLIBCXX_3.4.21' not found` problem, 
remember to do make clean // rm CMakeCache.txt // rm -r build 
before remake densepose.
